# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='lng',
        ),
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, default='game_images/default.png', upload_to='game_images'),
        ),
    ]
